language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
#  - jruby-19mode # JRuby in 1.9 mode -> Problems with bigint
#  - rbx-19mode

script:
  bundle exec rake

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgsl0-dev
